### PR TITLE
feat: add dev/prod secrets functionality

### PR DESCRIPTION
**Pull request by joshua-mo-143**
* Local deployments now use `Secrets.dev.toml` by default

* Added a flag to `run_args` that allows usage of prod secrets in a local deployment should the user need to do so

Ref: Issue #563 

Notes:
I was thinking about using `Secrets.prod.toml` as a filename for live deployment but it will probably break any and all deployments currently using `Secrets.toml`, as well as there being an example project in testing that currently uses `Secrets.toml`, so until there's further consideration about how to deal with live deployments that currently use secrets it's probably a good idea to leave this unchanged until a discussion on how to solve this has been made.

### CODE REVIEW

**Comment by jonaro00** [comment]
I suggest that the flag should instead be called -r / --release (and therefore at the same time implement #609), so that a local release build will be run when using local production secrets. (This makes the most sense at least, but perhaps the prod_secrets flag could be separate from --release, and implied when using --release)

**Comment by joshua-mo-143** [comment]
> I suggest that the flag should instead be called -r / --release (and therefore at the same time implement #609), so that a local release build will be run when using local production secrets. (This makes the most sense at least, but perhaps the prod_secrets flag could be separate from --release, and implied when using --release)

I think `prod_secrets` should probably be kept separate from `--release` as in my mind they're two entirely separate things and I'd personally like to keep modularity in mind. Maybe we could create an entirely new flag called `simulate_prod` that combines both of these flags together?

**Comment by oddgrd** [comment]
We'll go with just defaulting to the `Secrets.dev.toml` file if it exists for now, without the CLI arg to enable prod secrets. If people want to use prod secrets locally it won't be difficult anyway. We can look at this again down the line as we keep improving the Secrets feature.

**Comment by joshua-mo-143** [comment]
Ok no worries, that's fine then - we can proceed as is

**Review by oddgrd — APPROVED** [review]
Great, thanks!

**Pull request merged**
