### PR TITLE
feat: Handling regular signals sent to cargo-shuttle on Windows

### PR DESCRIPTION
**Pull request by Shubham8287**
## Description of change
Gracefully handling windows signal to interrupt local run for #872.
/claim #872

## How has this been tested? (if applicable)
Tested by running on windows, with Ctrl+C

### CODE REVIEW

**Comment by Shubham8287** [comment]
Right now Implemented handler for Ctrl+C only, it can be extended to other ones. Would love to get some input on which one to add from https://docs.rs/tokio/latest/tokio/signal/windows/index.html.
Also, Signal handler looks is mostly repeated for Unix and windows and between different handlers. Will try to have signal handling as wrapper or something.

**Comment by iulianbarbu** [comment]
I think we need to handle all of them: https://learn.microsoft.com/en-us/windows/console/setconsolectrlhandler#remarks. A default handler for all these signals calls `ExitProcess`.

**Comment by Shubham8287** [comment]
Added all the handlers, please review

**Comment by iulianbarbu** [comment]
Seems like tests are failing because of `cargo fmt`. Can you fix it?

**Comment by Shubham8287** [comment]
@iulianbarbu  passed all checks now.

**Comment by iulianbarbu** [comment]
Thanks @Shubham8287 ! We just need to do some manual testing on a windows machine. We'll follow up after.

**Review by iulianbarbu — APPROVED** [review]
Testing worked well on my side @Shubham8287 ! thanks.

**Pull request merged**
