### PR TITLE
ci: add Makefile command for Windows to convert .sh files to LF format

### PR DESCRIPTION
**Pull request by joshua-mo-143**
+ add makefile command to convert .sh files to Unix format
+ add relevant documentation in CONTRIBUTING.md

Explanation:
As noted in the CONTRIBUTING.md file, the Makefile currently does not play nicely with Windows and you'll have to set up using WSL/Bash to get anything to work. This isn't necessarily a problem in of itself as you currently need WSL anyway to run Docker Desktop; however, Windows seems to pull files from Git repos in CRLF format rather than LF format which is inconvenient as it breaks `make images`. The added script is intended to simply install dos2unix and then convert the .sh files to Unix format so that `make images` can properly read the .sh files. Relevant documentation has also been added to CONTRIBUTING.MD to explain all of this.

### CODE REVIEW

**Comment by oddgrd** [comment]
Thanks for this Josh, it's about time we have someone look into our windows issues :smile:. I'm wondering though, have you explored tweaking this git setting: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf? It might be an even easier solution. :crossed_fingers:

**Comment by joshua-mo-143** [comment]
Oh, I didn't know that actually existed! That would probably be a more convenient solution, do you want me to add that instead then?

**Comment by oddgrd** [comment]
I haven't tried it myself, but if it works I think that would be great, yeah. :pray:

**Comment by joshua-mo-143** [comment]
It looks like the Git commands work, so I've made the required changes and squashed all commits into one final commit. If/when this gets approved, I'll make sure to add matching documentation updates on the docs repo to match this one.

**Review by oddgrd — APPROVED** [review]
This is great, thanks Josh, and thanks for offering to update the docs too! I'm wondering, should we also include a link to [the git configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf)?

**Comment by joshua-mo-143** [comment]
Retroactively added the link to the git config page in the documentation for traceability purposes. I'm personally undecided on the issue as we've already addressed the main bulk of the relevant information in our own docs but it doesn't really hurt to add it since having a citation to help back up information always helps.

**Pull request merged**
