### PR TITLE
Add commands cookbook to cargo-shuttle --help

### PR DESCRIPTION
**Pull request by beyarkay**
This commit adds a couple of example `cookbook` style commands to the `--help` subcommand of `cargo-shuttle`. 

## Description of change
It took some time for me to realise the difference between `deploy` and `deployments`, or to discover that I could watch my logs in real time via `logs --follow`. My hope is that this extended help assists newcomers in figuring out what cargo-shuttle can do.

As a side note, I understand that this adds a bit of bloat to the help command, and maybe this sort of information is better off somewhere in the docs or in the descriptions for each of the subcommands, so feel free to close this PR if it does not fit in with the overall goals of where information should be.

### CODE REVIEW

**Review by oddgrd — COMMENTED** [review]
Hey @beyarkay, thanks for this! To me this feels a little bit redundant, but then again I am very familiar with the CLI :smile: We do have a page for the CLI in our docs, perhaps we should rather just add a link to that?

**Comment by jonaro00** [comment]
I agree that having cookbook examples in the help command is too much, but such a list of common ways to use commands are a good addition to the docs page. The link to the docs page can be included here.

**Comment by jonaro00** [comment]
@beyarkay The comment you have now does not appear in the help output. The general description at the top of help page is taken from cargo-shuttle/Cargo.toml.

**Comment by beyarkay** [comment]
Ahh this was a sneaky line to find.

**Review by jonaro00 — APPROVED** [review]
Neat!

**Review by iulianbarbu — APPROVED** [review]
LGTM! thanks 👍

**Pull request merged**
