### PR TITLE
chore(deps): bump base64 to 0.21.5

### LINKED ISSUE #1393: [Improvement]: Bump base64 dependency
### Describe the improvement

We are using `base64` dependency for auth tests and the version is outdated:

https://github.com/shuttle-hq/shuttle/blob/299a30db5b3361c328b3231971d8276d10995be7/Cargo.toml#L47

The tests can be run like this:

```sh
cargo test -p shuttle-common
```

The moral of the story is we can bump it but there are some breaking changes: https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md#0200

Feel free to comment on this issue if you want to work on it!

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

### PR DESCRIPTION
**Pull request by cassie-rust**
## Description of change
Bumps `base64` version to 0.20.0, which contains breaking changes from 0.13.1

This PR only updates existing tests, which didn't compile with the upgrade.

I did not find any existing tests for url-unsafe characters, and I feel it's not my place to decide on the necessity of them -- I leave that to the maintainers to decide; there is a subtle difference in behavior, as explained here: https://github.com/marshallpierce/rust-base64/issues/206#issuecomment-1354016644

Closes #1393

## How has this been tested? (if applicable)
I ran `cargo test -p shuttle-common` before upgrade, and after. Both suites passed, which they shouldn't given the incompability. On trying to run the unit tests themselves, it failed, silently. Running the tests from vscode produces the following:

```
Executing task: cargo test --package shuttle-common --lib -- backends::auth::tests --nocapture 

    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests src/lib.rs (target/debug/deps/shuttle_common-28e6d65a277dfe89)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.00s
```
I've yet to successfully even /run/ these tests, and I'm at my wit's end. However, `cargo clippy` will try and compile and blow up because of incompatibilities and so I used that as a guide. It compiles, but it has not been tested.

### CODE REVIEW

**Review by orhun — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by oddgrd** [comment]
Thanks @cassie-rust, this looks great! I'm wondering, should we upgrade to the latest version (currently 0.21.5)?

You'll need some feature flags enabled to run the tests: `cargo test -p shuttle-common --features backend,service,display` (or `--all-features`). They pass :partying_face:

**Comment by cassie-rust** [comment]
Sure, I can do that; it seems to mostly be namespace changes between 0.20 and 0.21

**Comment by oddgrd** [comment]
Cool!

**Comment by cassie-rust** [comment]
Bumped to 0.21.5 instead.

**Review by jonaro00 — APPROVED** [review]
Thanks!

**Pull request merged**
