### PR TITLE
feat: pre-installed build environment in deployer

### LINKED ISSUE #807: [Feature]: pre-installed environment on `deploy` build machines
### Describe the feature

This is related to #703.

It is not uncommon that a project may depend on crates that wrap code in other languages.
To have a hassle free experience at least the build tools for the most common cases should be installed on the machine that handles the `shuttle deploy` build step. 

I would assume this to be at least what a GH runner comes pre-installed with.

See [here](https://github.com/actions/runner-images#software-and-image-support) for what this entails on the resp. target platform/OS.

I would suggest starting with a C/C++ compiler and I would have some projects to test this.

### Suggestion or Example of how the feature would be used

_No response_

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

### PR DESCRIPTION
**Pull request by jonaro00**
## Description of change

Closes #807.

Added some common (C) build tools when installing deployer.
This allows crates such as `audiopus` to build.

If there are more tools needed, they can be suggested or added in subsequent PRs.

## How has this been tested? (if applicable)

Deployed a crate with `audiopus v0.2.0` locally. https://crates.io/crates/audiopus/

### CODE REVIEW

**Review by oddgrd — COMMENTED** [review]
Thanks! For the new builder we intend to allow easy configuration of build dependencies, but this will be good to have in the meantime. I do believe we have some of the ones you added covered already though, since we use a rust image with the [buster](https://github.com/docker-library/buildpack-deps/blob/65d69325ad741cea6dee20781c1faaab2e003d87/debian/buster/Dockerfile) buildpack-deps.

**Comment by jonaro00** [comment]
Is build time env vars planned aswell?

**Comment by oddgrd** [comment]
You mean like --cfg flags to rustc (https://github.com/shuttle-hq/shuttle/issues/928), or more than that? @chesedo is working on the new builder as we speak, so it would be great to hear what functionality you'd like to see in this regard!

**Comment by jonaro00** [comment]
Sooner or later there will be dependencies that need env vars at build time for arbitrary purposes. Secrets come in too late for that. While .cargo/config.toml can fix flags to rustc, some users will want to set env vars.
https://discord.com/channels/803236282088161321/1107140940759568384/1107511887157022820

(p.s this PR should be ready)

**Review by oddgrd — APPROVED** [review]
Alright, thanks! We'll keep it in mind for the builder.

**Comment by jonaro00** [comment]
You can also consider the possibility of running an arbitrary script (install third party deps) before compilation starts.

**Comment by oddgrd** [comment]
I think since we're using nix for the builder adding third-party deps should be quite straightforward with nix derivations.

**Pull request merged**
