### PR TITLE
feat: support underscore in project name

### PR DESCRIPTION
**Pull request by coszio**
## Motivation 

As suggested in #262, naming a project subdomain should allow underscores within the name in the same way it allows hyphens.

In the issue it is stated that the intention is to harmonize with crate naming, but such naming is a still ongoing discussion whether `kebab-case` or `snake_case` should be recommended ([which can be seen here](https://github.com/rust-lang/api-guidelines/discussions/29)). Since one or the other is not standardized, I think shuttle should allow the underscore as well.

## Implementation

Underscores are treated in the same way as hyphens: they can only be within the name of the subdomain, not at the end nor at the start. 
Also, when looking at the code I swapped the implementation of a valid character with a `matches!` macro to use more idiomatic Rust.

### CODE REVIEW

**Review by chesedo — APPROVED** [review]
Nice, and thanks for the match cleanup @coszio

**Comment by chesedo** [comment]
@coszio this just needs a quick `cargo fmt --all`

**Comment by coszio** [comment]
@chesedo Totally missed it

**Comment by coszio** [comment]
This also closes #262, forgot to add it in the description :)

**Pull request merged**
